### PR TITLE
Gh 7

### PR DESCRIPTION
**Pull request by brandonStell**

### CODE REVIEW

**Comment by brandonStell** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.5.27](https://github.com/PubPeerFoundation/pubpeer_zotero_plugin/releases/download/builds/zotero-pubpeer-0.0.5.27.xpi) ("Merge pull request #8 from PubPeerFoundation/gh-7\n\nGh 7")

Install in Zotero by downloading [test build 0.0.5.27](https://github.com/PubPeerFoundation/pubpeer_zotero_plugin/releases/download/builds/zotero-pubpeer-0.0.5.27.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
?

**Comment by brandonStell** [comment]
Oops, did I do this wrong?  I thought I was supposed to merge...

**Comment by retorquere** [comment]
No problem. It seemed safe to merge for me, but I was waiting for confirmation.

**Comment by retorquere** [comment]
I (or you) can cut a release once it's merged. I usually merge from my own clone rather than through a pull request, but it does the same thing.

**Pull request merged**
